define usagi = Character("Usagi", color="#fd7979", image="usagi")
define takeshi = Character("Takeshi", color="#44bbff", image="takeshi")
define sanders = Character("Sanders", color="#00ff00", image="sanders")
define kelisha = Character("Professor Kelisha", color="#0000ff", image="kelisha")
define child = Character("Child", color="#dddddd", image="child")
define bart = Character("Barthandelus", color="#6600dd", image="bart")
define jojo = Character("Professor Jojo", color="#666666", image="jojo")