name: build and release

on:
  # for now, build and release on every change. 
  # if our assets get very large, this might use up our (free) quotas quickly -
  # but let's wait and worry about that when/if it happens.
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build-and-deploy-desktop:
    runs-on: ubuntu-latest
    steps:
      # checkout, including lfs files (our gdrive assets)
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs pull
      - run: ./bin/ci

      ## desktop build and deploy to github releases
      - run: ./bin/build-desktop
      - uses: remarkablegames/setup-butler@v3
      - env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./bin/deploy-desktop

  build-and-deploy-web:
    runs-on: ubuntu-latest
    environment:
      name: itch.io web
      url: "https://erosson.itch.io/otaku-oratorio-2026?secret=Ej4ArGlmXwr1HcR3SCoDkI4UyL8"
    steps:
      # checkout, including lfs files (our gdrive assets)
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs pull
      - run: ./bin/ci

      # web build and deploy to itch.io
      # https://erosson.itch.io/otaku-oratorio-2026
      - run: ./bin/build-web
      - uses: remarkablegames/setup-butler@v3
      - env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./bin/deploy-web
